### ISSUE TITLE
Error on nvim start

### ISSUE THREAD

**Issue by gegoune** [andersevenrud/compe-tmux#4] opened 2021-06-25 16:03 UTC
Hi, amazing plugin, proved useful quite a few times already!

I am in the process of refactoring my nvim configuration and am no longer using packer's `config` keys to configure plugins. I simply have packer to install them all into `…/site/pack/packer/start` and using `after/plugin/*` to configure/initialise plugins.

I have run into an issue with compe-tmux, where it would error at nvim's start:

```
Error detected while processing /Users/<me>/.local/share/nvim/site/pack/packer/start/compe-tmux/after/plugin/compe_tmux.vim:
line    7:
E5108: Error executing lua ...vim/site/pack/packer/start/compe-tmux/lua/compe_tmux.lua:127: attempt to index field 'source' (a nil value)
```

I do have compe installed and working, configuration contains, amongst other options:

```lua
require("compe").setup {                                             
  preselect = "always",                                              
  source = {                                                         
    path = true,      
    buffer = true,                                                   
    vsnip = true,                                                    
    nvim_lsp = {true,  
    spell = { filetypes = { "mail", "gitcommit" } },                 
    tmux = true,                                                     
  },                                                                 
}                                                                    
```

Do you think that might but in cobpe-tmux or simply some mistake in my setup? Thanks!

**Comment by andersevenrud** [comment] 2021-06-25 16:22
To me this seems like maybe the tmux plugin loads before compe, which is why there's a `nil` exception there. I'll look to see if maybe there's a lazy loading method that can be adapted here :thinking:

**Comment by gegoune** [comment] 2021-06-25 16:43
I have also tried to put compe-tmux in `opt/` to avoid premature load as I had the same suspicion.
I then initialised it with:

```lua
vim.cmd "packadd compe-tmux"                                  
require("compe").register_source("tmux", require "compe_tmux")

require("compe").setup { …}
```
but it resulted in the same error.

Then after switching order I did get it to work:

```lua
vim.cmd "packadd compe-tmux"                                  

require("compe").setup { …}
require("compe").register_source("tmux", require "compe_tmux")
```

**Comment by andersevenrud** [comment] 2021-07-03 23:06
I've added a condition to prevent this exception from happening for others trying the same thing. Seeing that you figured out to load things in the correct order I'm closing this issue.

**Comment by gegoune** [comment] 2021-07-04 08:45
FYI, I am still getting that error with latest versions of compe and compe-tmux on nvim-0.5

```
Error detected while processing /Users/<me>/.local/share/nvim/site/pack/packer/start/compe-tmux/after/plugin/compe_tmux.vim:
line    7:
E5108: Error executing lua ...vim/site/pack/packer/start/compe-tmux/lua/compe_tmux.lua:132: attempt to index field 'source' (a nil value)
Press ENTER or type command to continue
```

I have moved compe-tmux back to `start/`, removed both `packadd` and `register_source()` call.

**Comment by andersevenrud** [comment] 2021-07-04 19:25
Okay. I'll replicate your setup and get to the bottom of that one :D

**Comment by gegoune** [comment] 2021-07-04 20:22
Thank you. Please let me know if there is anything you would like me to try. Loving that extension so would like to help as much as I can.

**Comment by andersevenrud** [comment] 2021-07-04 20:43
Maybe you could create a minimum example to reproduce this ? :)

**Comment by gegoune** [comment] 2021-07-05 18:17
It's very interesting. I have tried to reproduce it with minimal rc, but couldn't. It just works as expected with that config:

```lua
local fn = vim.fn

local install_path = "/tmp/site/pack/packer/start/packer.nvim"

vim.opt.packpath = "/tmp/site/pack/packer"
vim.opt.runtimepath = install_path
vim.opt.runtimepath:append("/usr/local/Cellar/neovim/HEAD-f515bae/share/nvim/runtime")

if fn.empty(fn.glob(install_path)) > 0 then
	vim.api.nvim_command("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
end

vim.opt.termguicolors = true

require("packer").startup({
	function(use)
		use({ "wbthomason/packer.nvim" })
		use({ "hrsh7th/nvim-compe" })
		use({ "andersevenrud/compe-tmux" })
	end,
	config = { package_root = "/tmp/site/pack" },
})

require("compe").setup({
	source = {
		tmux = true,
	},
})
```

One difference I noticed is that in nvim instance running of minimal config file I do get `…/{nvim-compe,compe-tmux}/after` paths in `runtimepath` while they are not there in my regular config. I tried to append those paths at the top of my regular `init.lua` but it didn't make the load error go away.

```lua
vim.opt.runtimepath:append "~/.local/share/nvim/site/pack/packer/start/compe-tmux/after"
vim.opt.runtimepath:append "~/.local/share/nvim/site/pack/packer/start/nvim-compe/after"
```
and they actually do not appear in `set runtimepath?`'s output. I will keep on digging into my set up.

**Comment by andersevenrud** [comment] 2021-07-05 18:35
> while they are not there in my regular config. I tried to append those paths at the top of my regular init.lua but it didn't make the load error go away.

That certainly is quite interesting.

I haven't run into any issues relating to `runtimepath`, however `packpath` gave such a headache when I switched to packer. Even though the values there were OK, I could not get packer to load. And after I somehow got that to work, plugins just launched with a bunch errors, which just suddenly went away on its own. I started from scratch in order to satisfy my curiosity and then it suddenly worked fine, with the exact same procedure as before :man_shrugging:

**Comment by gegoune** [comment] 2021-07-05 18:45
One more thing that might be worth mentioning that is different in minimal and my regular configs: compe' configuration location is in minimal rc, while in my config it is in `after/plugin`, so I assume loading order is to be looked at a bit more.

**Comment by andersevenrud** [comment] 2021-07-29 20:32
Any luck ? :sweat_smile:

**Comment by gegoune** [comment] 2021-07-29 20:47
Hey, sorry, completely forgot about it and just kept my little `opt/` and `packadd` workaround. :)

**Comment by andersevenrud** [comment] 2021-07-29 20:52
Ah, no worries.

I'm just doing a little cleanup of open issues in my repos, so I thought I'd give a poke. Maybe it's safe to close this issue ?

**Comment by gegoune** [comment] 2021-07-29 21:04
Yeah, sure, close away. :) Out of curiosity, were you able to reproduce my issue at all?

**Comment by andersevenrud** [comment] 2021-07-29 21:10
Nope, I was not able to reproduce this :/

**Closed by andersevenrud** 2021-07-29 21:10 UTC

**Comment by gegoune** [comment] 2021-08-09 21:32
Have installed another (second, had yours only before) compe's extension. [codybuell/compe-lbdb](https://github.com/codybuell/compe-lbdb) - for whatever reason I am not having the same issue with compe-lbdb. Just letting you know in case it could help somehow.

My Packer's configuration for those plugins is as such:

```lua
use { 'hrsh7th/nvim-compe', requires = { { 'andersevenrud/compe-tmux', opt = true }, { 'codybuell/compe-lbdb' } } }
```

**Comment by andersevenrud** [comment] 2021-08-09 21:41
Looked at how that extension is handling the configuration loading (which is what the source of the exception is) and it has some kind of reducer that does not has any error side effects.

Currently trying a similar approach.

**Comment by andersevenrud** [comment] 2021-08-09 21:49
Actually, I just decided to add another check into the configuration loading. Should take care of the problem once and for all...

**Comment by gegoune** [comment] 2021-08-09 21:59
And it does work now without my little work around! I am glad I thought of letting you know! Sorry for pinging you in closed issue and thanks for both great plugin and fixing my issue!

**Comment by andersevenrud** [comment] 2021-08-09 22:04
No worries! Thanks for chiming in.

Would love to get to get to the bottom of this stiff though, heh. The only thing I can think of is that compe-tmux somehow is loaded twice, and once too early which leads to this exception. Technically it shouldn't because the Lua module system (i.e. `require`) is cached :shrug: 

But at least there's no more error.
